#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.png"
# use `px` or `x` with logo_width, example: "100px".
# Note: logo_width is not work with .svg file
logo_width = "200px"
# if logo_webp set false, will not generate WEBP version of logo | default is true
logo_webp = true
# logo text will only show when logo is missing.
logo_text = "Microcks"
# purgeCSS
purge_css = true
# image gallery shortcode
image_gallery = true
# contact form action
contact_form_action = "#" # contact form works with [https://airform.io/] or [https://formspree.io]
# google tag manager, see https://developers.google.com/tag-manager/
google_adsense = "" # example: ca-pub-xxxxxxxxxxxxxxxx
google_tag_manager = "" # example: G-XXXXXXXXXX
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>"
custom_script = ""
# table of content on document page
table_of_content = true
# copyright
copyright = "The Linux Foundation® (TLF) has registered trademarks and uses trademarks. For a list of TLF trademarks, see [**Trademark Usage**.](https://www.linuxfoundation.org/legal/trademark-usage) <br> **Microcks** is a [**Cloud Native Computing Sandbox**](https://landscape.cncf.io/?selected=microcks) project 🚀"
theme_copyright = false

# Preloader
[preloader]
enable = true 
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[[nav_button]]
#style = "outline"   # available style: solid, outline
style = "solid"
label = "♻️ 1.7.1 has just been released! 🚀"
link = "https://microcks.io/blog/microcks-1.7.1-release/"

#[[nav_button]]
#label = "Contact" 
#link = "contact/" 
#style = "solid" # available style: solid, outline

# call to action
[call_to_action]
enable  = true
title  = "Still Didn't Find Your Answer?"
#image  = "images/none.jpg" # image do not exists, hack to not have a missing icon on the site 
# image source: https://medium.com/nerd-for-tech/why-should-you-get-involved-in-an-open-source-community-f5516657324
# droit???
image = "images/cta-illustration.jpg"
content = "Join our community and get the help you need. Engage with other members, ask questions, and share knowledge to resolve your queries and expand your understanding."


[call_to_action.button]
enable  = true
label  = "Join the community"
link  = "https://microcks.io/community/"

# Crisp Chat
[crisp_chat]
crisp_website_id = "9aa449e1-9999-422a-938f-8567982eec6d" # replace this code with yours
enable = false 
# Check this video tutorial to get your crisp website ID - https://www.youtube.com/watch?v=nW5UX6iVdFc

# seo meta data for OpenGraph / Twitter Card
[metadata]
author = "GetHugoThemes" 
description = "This is meta description" 
image = "images/favicon.png" # this image will be used as fallback if a page has no image of its own
keywords = ["Boilerplate", "Hugo", "Themefisher", "GetHugoThemes"] 

# matomo tracking: see https://matomo.org/
[matomo]
enable = false 
id = "" # your matomo id
url = "" # your matomo url

# baidu analytics: see https://tongji.baidu.com/
[baidu]
analytics_id = "" # Your ID
enable = false 

# plausible analytics: see https://plausible.io/
[plausible]
domain = "" # yourdomain.com
enable = false 

# counter analytics: see https://counter.dev/setup.html
[counter]
enable = false 
username = "" # your username

# site verifications
[site_verification]
baidu = "" # Your verification code
bing = "" # Your verification code
facebook = "" # Your verification code
google = "" # Your verification code
mastodon = "" # Your verification code

# cookies
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = true
expire_days = 2

############################# social site ########################
[[social]]
title = "GitHub"
icon = "fab fa-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/microcks"

[[social]]
title = "LinkedIn"
icon = "fab fa-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/company/microcks/"

[[social]]
title = "Twitter"
icon = "fab fa-twitter" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/microcksio"

#[[social]]
#title = "Mastodon"
#icon = "fab fa-mastodon" # themify icon : https://themify.me/themify-icons
#link = "https://hachyderm.io/@microcksio@mastodon.social"

[[social]]
title = "YouTube"
icon = "fab fa-youtube" # themify icon : https://themify.me/themify-icons
link = "https://www.youtube.com/c/Microcks"

[[social]]
title = "Slack"
icon = "fab fa-slack" # themify icon : https://themify.me/themify-icons
link = "https://cloud-native.slack.com/messages/microcks"
